config/routes.rb
Hashington::Application.routes.draw do
  resources :hashcodes

  root :to => "home#index"

  match 'login' => 'authentication#login'
  match 'logout' => 'authentication#logout'
  match 'register' => 'authentication#register'
end

app/models/hashcode.rb
class Hashcode < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :hashcodes

	before_save do
		self.password_hash = Digest::SHA256.hexdigest(password_hash)
	end

	validates_presence_of :email, :message => 'Please provide an email address.'
	validates_presence_of :password_hash, :message => 'Please provide a password.'
	validates_confirmation_of :password_hash, :message => 'Passwords do not match.'
	validates_format_of :email, :with => /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}/, :message => 'That is not an email address!'
	validates_uniqueness_of :email, :case_sensitive => false, :message => 'There is already an account with that email address.'

	def self.authenticate_without_password_hash(username, password)
		if password.nil? or password.empty?
			return nil
		end

		# Just hash the fucker and get outta here.
		password_hash = Digest::SHA256.hexdigest(password)

		return authenticate_with_password_hash(username, password_hash)
	end

	def self.authenticate_with_password_hash(username, password_hash)
		return find(:first, :conditions => "email = '#{username}' AND password_hash = '#{password_hash}'")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  before_filter :restore_session

  protect_from_forgery

  def ensure_login
	unless @current_user
		redirect_to login_path
	end
  end

  def restore_session
	unless session[:user_id].nil?
		@current_user = User.find(session[:user_id])
	end
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
	def login
		@user = User.authenticate_without_password_hash(params[:username], params[:password])

		unless @user.nil?
			session[:user_id] = @user.id

			redirect_to root_path
		end
	end

	def logout
		unless @current_user.nil?
			session[:user_id] = nil

			redirect_to root_path
		else
			raise
		end
	end

	def register
		if request.post?
			@user = User.new(:email => params[:username], :password_hash => params[:password], :password_hash_confirmation => params[:password_confirmation])

			if @user.valid? and @user.save
				session[:user_id] = @user.id

				redirect_to root_path
			end
		end
	end
end

app/controllers/hashcodes_controller.rb
class HashcodesController < ApplicationController
  before_filter :ensure_login

  # GET /hashcodes
  # GET /hashcodes.xml
  def index
    @hashcodes = @current_user.hashcodes

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @hashcodes }
    end
  end

  # GET /hashcodes/1
  # GET /hashcodes/1.xml
  def show
    @hashcode = Hashcode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @hashcode }
    end
  end

  # GET /hashcodes/new
  # GET /hashcodes/new.xml
  def new
    @hashcode = @current_user.hashcodes.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @hashcode }
    end
  end

  # GET /hashcodes/1/edit
  def edit
    @hashcode = Hashcode.find(params[:id])
  end

  # POST /hashcodes
  # POST /hashcodes.xml
  def create
	if params[:email].nil?
		@user = @current_user
	else
		@user = User.find_by_email(params[:email])

		# Create a new user with this email address...if one hasn't be found of course.
		if @user.nil?
			@user = User.new(:email => params[:email])
			@user.save
		end
	end

	# Need to generate a new hash code.
	@hashcode = @user.hashcodes.new(:hash => generate_hash, params[:inital_value], :current_value => params[:initial_value])

    respond_to do |format|
      if @hashcode.save
        format.html { redirect_to(@hashcode, :notice => 'Hashcode was successfully created.') }
        format.xml  { render :xml => @hashcode, :status => :created, :location => @hashcode }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @hashcode.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /hashcodes/1
  # PUT /hashcodes/1.xml
  def update
    @hashcode = Hashcode.find(params[:id])

    respond_to do |format|
      if @hashcode.update_attributes(params[:hashcode])
        format.html { redirect_to(@hashcode, :notice => 'Hashcode was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @hashcode.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hashcodes/1
  # DELETE /hashcodes/1.xml
  def destroy
    @hashcode = Hashcode.find(params[:id])
    @hashcode.destroy

    respond_to do |format|
      format.html { redirect_to(hashcodes_url) }
      format.xml  { head :ok }
    end
  end

	def generate_hash
		# pick two sets of 5 letters & numbers
		a = ("a".."z").to_a
		(0..9).each { |i| a << i }

		hash = ""
		for i in (0..10)
			hash << a.at(rand(a.length)).to_s

			if i == 5
				hash << "-"
			end
		end

		if not Hashcode.find_by_hash(hash).nil?
			return generate_hash
		else
			return hash
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def is_logged_in?
		not @current_user.nil?
	end
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/hashcodes_helper.rb
module HashcodesHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authentication/login.html.erb
<h1>Login</h1>

<% if request.post? and @user.nil? %>
	<ul class="errors">
		<li>Wrong email address or password, man.</li>
	</ul>
<% end %>

<% form_tag('/login', :method => 'post') do %>
	<div class="email"><%= label_tag :username, "Email:" %> <%= email_field_tag :username %></div>
	<div class="password"><%= label_tag :password, "Password:" %> <%= password_field_tag :password %></div>

	<div class="buttons">
		<%= submit_tag 'Login' %> <%= link_to 'Register', '/register' %>
	</div>
<% end %>

app/views/authentication/register.html.erb
<h1>Register</h1>

<% if request.post? and not @user.errors.empty? %>
<ul class="errors">
	<% @user.errors.each do |element,msg| %>
		<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<% form_tag('/register', :method => 'post') do %>
	<div class="email"><%= label_tag :username, "Email:" %> <%= email_field_tag :username %></div>
	<div class="password"><%= label_tag :password, "Password:" %> <%= password_field_tag :password %></div>
	<div class="confirm-password"><%= label_tag :password_confirmation, "Confirm Password:" %> <%= password_field_tag :password_hash_confirmation %></div>

	<div class="buttons">
		<%= submit_tag 'Register' %> <%= link_to 'Cancel', root_path %>
	</div>
<% end %>

app/views/hashcodes/_form.html.erb
<%= form_for(@hashcode) do |f| %>
  <% if @hashcode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hashcode.errors.count, "error") %> prohibited this hashcode from being saved:</h2>

      <ul>
      <% @hashcode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hash %><br />
    <%= f.text_field :hash %>
  </div>
  <div class="field">
    <%= f.label :pin %><br />
    <%= f.text_field :pin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hashcodes/edit.html.erb
<h1>Editing hashcode</h1>

<%= render 'form' %>

<%= link_to 'Show', @hashcode %> |
<%= link_to 'Back', hashcodes_path %>

app/views/hashcodes/index.html.erb
<% unless is_logged_in? %>
	<h2>Please log in to do something!</h2>
<% else %>
	<h2>Your Hash Codes</h2>

	<table>
		<tr>
			<th>Code</th>
			<th>Current Value</th>
		</tr>

	<% unless @current_user.hashcodes.empty? %>
		<% @current_user.hashcodes.each do |code| %>
		<tr>
			<td><%= code.hash %></td>
			<td><%= code.current_value %></td>
		</tr>
		<% end %>
	<% else %>
		<tr>
			<td colspan="2">How sad, you don't have any hash codes.</td>
		</tr>
	<% end %>

	</table>

	<h2>Add a Hash Code</h2>

	<div class="new-hashcode">
	<%= form_tag hashcodes_path do %>
		<%= label_tag :email, 'Email:' %> <%= text_field_tag :email %>

		<%= label_tag :initial_amount, 'Initial Amount:' %> <%= text_field_tag :initial_amount %>

		<div class="buttons">
			<%= submit_tag 'Create New Hashcode' %>
		</div>
	<% end %>
	</div>
<% end %>

app/views/hashcodes/new.html.erb
<h1>New hashcode</h1>

<%= render 'form' %>

<%= link_to 'Back', hashcodes_path %>

app/views/hashcodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hash:</b>
  <%= @hashcode.hash %>
</p>

<p>
  <b>Pin:</b>
  <%= @hashcode.pin %>
</p>


<%= link_to 'Edit', edit_hashcode_path(@hashcode) %> |
<%= link_to 'Back', hashcodes_path %>

app/views/home/index.html.erb
<% unless is_logged_in? %>
	<h2>Please log in to do something!</h2>
<% else %>
	<h2>Your Hash Codes</h2>
	
	<table>
		<tr>
			<th>Code</th>
			<th>Current Value</th>
		</tr>
		
	<% unless @current_user.hashcodes.empty? %>
		<% @current_user.hashcodes.each do |code| %>
		<tr>
			<td><%= code.hash %></td>
			<td><%= code.current_value %></td>
		</tr>
		<% end %>
	<% else %>
		<tr>
			<td colspan="2">How sad, you don't have any hash codes.</td>
		</tr>
	<% end %>
	
	</table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hashington</title>

  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <% if is_logged_in? %>
	<%= @current_user.email %> | <%= link_to 'Logout', '/logout' %>
  <% else %>
	<%= link_to 'Login', '/login' %> | <%= link_to 'Register', '/register' %>
  <% end %>

<%= yield %>

</body>
</html>